version: 2

sources:
  - name: default
    database : workspace
    description: test dataset

    tables:
      - name: reseau_deau_potable_conduite
        columns:
          - name: cond_id
            tests:
              - unique
              - not_null

      - name: eau_evolution_des_prelevements_en_eau_pour_les_besoins_du_territoire_parisien
        columns:
          - name: annee
            description : annee observation